name: lpshipit # you probably want to 'snapcraft register <name>'
version: '0.5.2' # just for humans, typically '1.2+git' or '1.3.2'
base: core20
summary: Helpful utility for merging and testing launchpad MPs # 79 char long summary
description: |
  Helpful utility for merging and testing launchpad MPs (only works for git repos)

grade: stable
confinement: classic
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  lpshipit:
    plugin: python
    source: .
    source-type: git
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    python-packages:
      - launchpadlib
    stage-packages:
      - python3-wheel

apps:
  lpshipit:
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$PYTHONPATH
    command: bin/lpshipit
  lpmpmessage:
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$PYTHONPATH
    command: bin/lpmpmessage
  lpmptox:
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$PYTHONPATH
    command: bin/lpmptox

